export const ENTITY_LIST_STYLES = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    height: 'calc(100vh - 42px)',
    p: 0,
    width: '100%',
    position: 'relative',
    overflow: 'auto'
  },
  contentBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    flex: 1,
    width: '100%',
    px: 0,
    position: 'relative',
    height: 'auto',
  },
  gridContainer: {
    width: '100%',
    flex: 1,
    mt: 0,
    overflow: 'visible'
  },
  gridWrapper: {
    height: '100%',
    width: '100%',
    boxSizing: 'border-box' as const,
    overflow: 'visible'
  },
  actionCell: {
    position: 'relative',
    width: '200px',
    height: '30px'
  },
  actionCellBody: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '220px',
    height: '30px',
    backgroundColor: 'rgba(255,255,255,0)',
    borderStyle: 'solid',
    borderColor: 'rgba(247, 247, 246, 1)',
    borderWidth: '0 1px 1px 0',
    borderRadius: 0,
    background: 'inherit',
    boxSizing: 'border-box',
  },
  editButton: {
    position: 'absolute',
    top: '4px',
    left: '4px',
    width: '31px',
    height: '22px',
    padding: 0,
    backgroundColor: 'rgba(255,255,255,0)',
    border: 'none',
    borderRadius: '4px',
    '&:hover': { backgroundColor: 'rgba(0,0,0,0.04)' },
  },
  deleteButton: {
    position: 'absolute',
    top: '4px',
    left: '50px',
    width: 31,
    height: 22,
    padding: 0,
    backgroundColor: 'rgba(255,255,255,0)',
    border: 'none',
    borderRadius: '4px',
    '&:hover': { backgroundColor: 'rgba(0,0,0,0.04)' },
  },
  toggleSwitchContainer: {
    width: 30,
    height: 14,
    position: 'absolute',
    top: '7px',
    left: '52px'
  },
  configureButton: {
    position: 'absolute',
    top: '4px',
    left: '110px',
    width: '78px',
    height: '22px',
    textTransform: 'none',
    fontSize: '10px',
    fontWeight: 400,
    fontFamily: "'InterTight-Regular', 'Inter Tight', sans-serif",
    color: '#5B6061',
    minWidth: 0,
    padding: 0,
    backgroundColor: 'rgba(255,255,255,0)',
    border: 'none',
    borderRadius: '4px',
    justifyContent: 'center',
  }
};
