import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import FinancialYearFormatPanel from '../../../../src/components/common/FinancialYearFormatPanel/FinancialYearFormatPanel';
import { FINANCIAL_YEAR_FORMAT_OPTIONS, MONTHS } from '../../../../src/constants/periodSetupConstants';
import { generateFinancialYearName, calculateFinancialYearYears } from '../../../../src/utils/formatUtils';

// Mock the FormatPanel component
jest.mock('../../../../src/components/common/FormatPanel/FormatPanel', () => {
  return function MockFormatPanel({ 
    isOpen, 
    onClose, 
    onSave, 
    title, 
    formatOptions, 
    currentFormat, 
    previewText, 
    hasAutoGeneratedContent, 
    generatePreview 
  }: any) {
    return (
      <div data-testid="format-panel">
        <div data-testid="format-panel-title">{title}</div>
        <div data-testid="format-panel-current-format">{currentFormat}</div>
        <div data-testid="format-panel-preview-text">{previewText}</div>
        <div data-testid="format-panel-has-auto-generated">{hasAutoGeneratedContent.toString()}</div>
        <div data-testid="format-panel-is-open">{isOpen.toString()}</div>
        <div data-testid="format-panel-options-count">{formatOptions.length}</div>
        <button data-testid="format-panel-close" onClick={onClose}>Close</button>
        <button data-testid="format-panel-save" onClick={() => onSave(currentFormat)}>Save</button>
        <button data-testid="format-panel-generate-preview" onClick={() => generatePreview && generatePreview('FY {yy} - {yy}')}>Generate Preview</button>
      </div>
    );
  };
});

// Mock the utility functions
jest.mock('../../../../src/utils/formatUtils', () => ({
  generateFinancialYearName: jest.fn(),
  calculateFinancialYearYears: jest.fn(),
}));

// Mock the constants
jest.mock('../../../../src/constants/periodSetupConstants', () => ({
  FINANCIAL_YEAR_FORMAT_OPTIONS: [
    { value: 'FY {yy} - {yy}', label: 'FY {yy} - {yy}', isDefault: true },
    { value: 'FY {yyyy} - {yy}', label: 'FY {yyyy} - {yy}', isDefault: false },
    { value: 'FY {yyyy} - {yyyy}', label: 'FY {yyyy} - {yyyy}', isDefault: false },
    { value: 'FY {yyyy}', label: 'FY {yyyy}', isDefault: false },
    { value: 'FY {yy}', label: 'FY {yy}', isDefault: false },
  ],
  MONTHS: [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ],
}));

const mockGenerateFinancialYearName = generateFinancialYearName as jest.MockedFunction<typeof generateFinancialYearName>;
const mockCalculateFinancialYearYears = calculateFinancialYearYears as jest.MockedFunction<typeof calculateFinancialYearYears>;

describe('FinancialYearFormatPanel', () => {
  const defaultProps = {
    isOpen: true,
    onClose: jest.fn(),
    onSave: jest.fn(),
    currentFormat: 'FY {yy} - {yy}',
    hasAutoGeneratedContent: true,
  };

  beforeEach(() => {
    jest.clearAllMocks();
    
    // Setup default mock implementations
    mockGenerateFinancialYearName.mockReturnValue('FY 24 - 25');
    mockCalculateFinancialYearYears.mockReturnValue({
      financialYearStart: 2024,
      financialYearEnd: 2025
    });
  });

  it('renders without crashing', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    expect(screen.getByTestId('format-panel')).toBeInTheDocument();
    expect(screen.getByTestId('format-panel-title')).toHaveTextContent('Financial Year Name Format');
  });

  it('passes correct props to FormatPanel', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    expect(screen.getByTestId('format-panel-title')).toHaveTextContent('Financial Year Name Format');
    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('FY {yy} - {yy}');
    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('true');
    expect(screen.getByTestId('format-panel-has-auto-generated')).toHaveTextContent('true');
    expect(screen.getByTestId('format-panel-options-count')).toHaveTextContent('5');
  });

  it('generates preview text with financial year data', () => {
    const financialYear = {
      startMonth: 'April',
      endMonth: 'March'
    };
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    expect(mockCalculateFinancialYearYears).toHaveBeenCalledWith('April', 'March', MONTHS);
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', 2024, 2025);
    expect(screen.getByTestId('format-panel-preview-text')).toHaveTextContent('FY 24 - 25');
  });

  it('generates preview text without financial year data', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });

  it('handles different current formats', () => {
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        currentFormat="FY {yyyy} - {yyyy}"
      />
    );
    
    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('FY {yyyy} - {yyyy}');
  });

  it('handles hasAutoGeneratedContent false', () => {
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        hasAutoGeneratedContent={false}
      />
    );
    
    expect(screen.getByTestId('format-panel-has-auto-generated')).toHaveTextContent('false');
  });

  it('handles isOpen false', () => {
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        isOpen={false}
      />
    );
    
    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('false');
  });

  it('calls onClose when close button is clicked', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    const closeButton = screen.getByTestId('format-panel-close');
    fireEvent.click(closeButton);
    
    expect(defaultProps.onClose).toHaveBeenCalledTimes(1);
  });

  it('calls onSave when save button is clicked', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    const saveButton = screen.getByTestId('format-panel-save');
    fireEvent.click(saveButton);
    
    expect(defaultProps.onSave).toHaveBeenCalledWith('FY {yy} - {yy}');
  });

  it('handles generatePreview function', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    const generatePreviewButton = screen.getByTestId('format-panel-generate-preview');
    fireEvent.click(generatePreviewButton);
    
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });

  it('handles financial year spanning two calendar years', () => {
    const financialYear = {
      startMonth: 'February',
      endMonth: 'January'
    };
    
    mockCalculateFinancialYearYears.mockReturnValue({
      financialYearStart: 2024,
      financialYearEnd: 2025
    });
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    expect(mockCalculateFinancialYearYears).toHaveBeenCalledWith('February', 'January', MONTHS);
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', 2024, 2025);
  });

  it('handles financial year within same calendar year', () => {
    const financialYear = {
      startMonth: 'January',
      endMonth: 'December'
    };
    
    mockCalculateFinancialYearYears.mockReturnValue({
      financialYearStart: 2024,
      financialYearEnd: 2024
    });
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    expect(mockCalculateFinancialYearYears).toHaveBeenCalledWith('January', 'December', MONTHS);
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', 2024, 2024);
  });

  it('handles missing financial year start month', () => {
    const financialYear = {
      startMonth: '',
      endMonth: 'March'
    };
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    // Should fallback to current year
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });

  it('handles missing financial year end month', () => {
    const financialYear = {
      startMonth: 'April',
      endMonth: ''
    };
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    // Should fallback to current year
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });

  it('handles null financial year', () => {
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={null}
      />
    );
    
    // Should fallback to current year
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });

  it('handles undefined financial year', () => {
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={undefined}
      />
    );
    
    // Should fallback to current year
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });

  it('handles different format options', () => {
    render(<FinancialYearFormatPanel {...defaultProps} />);
    
    expect(screen.getByTestId('format-panel-options-count')).toHaveTextContent('5');
  });

  it('handles component unmounting', () => {
    const { unmount } = render(<FinancialYearFormatPanel {...defaultProps} />);
    
    expect(() => unmount()).not.toThrow();
  });

  it('handles rapid open/close cycles', () => {
    const { rerender } = render(
      <FinancialYearFormatPanel {...defaultProps} isOpen={false} />
    );
    
    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('false');
    
    rerender(
      <FinancialYearFormatPanel {...defaultProps} isOpen={true} />
    );
    
    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('true');
    
    rerender(
      <FinancialYearFormatPanel {...defaultProps} isOpen={false} />
    );
    
    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('false');
  });

  it('handles different current formats with financial year data', () => {
    const financialYear = {
      startMonth: 'April',
      endMonth: 'March'
    };
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        currentFormat="FY {yyyy} - {yyyy}"
        financialYear={financialYear}
      />
    );
    
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yyyy} - {yyyy}', 2024, 2025);
  });

  it('handles generatePreview with different formats', () => {
    const financialYear = {
      startMonth: 'April',
      endMonth: 'March'
    };
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    const generatePreviewButton = screen.getByTestId('format-panel-generate-preview');
    fireEvent.click(generatePreviewButton);
    
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', 2024, 2025);
  });

  it('handles edge case with invalid month names', () => {
    const financialYear = {
      startMonth: 'InvalidMonth',
      endMonth: 'AnotherInvalidMonth'
    };
    
    mockCalculateFinancialYearYears.mockReturnValue({
      financialYearStart: 2024,
      financialYearEnd: 2025
    });
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    expect(mockCalculateFinancialYearYears).toHaveBeenCalledWith('InvalidMonth', 'AnotherInvalidMonth', MONTHS);
  });

  it('handles edge case with empty month names', () => {
    const financialYear = {
      startMonth: '',
      endMonth: ''
    };
    
    render(
      <FinancialYearFormatPanel 
        {...defaultProps} 
        financialYear={financialYear}
      />
    );
    
    // Should fallback to current year
    expect(mockGenerateFinancialYearName).toHaveBeenCalledWith('FY {yy} - {yy}', expect.any(Number), expect.any(Number));
  });
});



