import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import WeekNameFormatPanel from '../../../../src/components/common/WeekNameFormatPanel/WeekNameFormatPanel';

// Mock the FormatPanel component
jest.mock('../../../../src/components/common/FormatPanel/FormatPanel', () => ({
  __esModule: true,
  default: function MockFormatPanel(props: any) {
    return (
      <div data-testid="format-panel">
        <div data-testid="format-panel-title">{props.title}</div>
        <div data-testid="format-panel-current-format">{props.currentFormat}</div>
        <div data-testid="format-panel-preview">{props.previewText}</div>
        <div data-testid="format-panel-is-open">{props.isOpen ? 'true' : 'false'}</div>
        <div data-testid="format-panel-has-auto-generated">{props.hasAutoGeneratedContent ? 'true' : 'false'}</div>
        <button data-testid="format-panel-close" onClick={props.onClose}>Close</button>
        <button data-testid="format-panel-save" onClick={() => props.onSave('new-format')}>Save</button>
        <div data-testid="format-panel-options">
          {props.formatOptions?.map((option: any, index: number) => (
            <div key={index} data-testid={`format-option-${index}`}>
              {option.label} - {option.value}
            </div>
          ))}
        </div>
      </div>
    );
  }
}));

// Mock the constants
jest.mock('../../../../src/constants/periodSetupConstants', () => ({
  WEEK_NAME_FORMAT_OPTIONS: [
    { value: '{ww}', label: 'Week Number (ww)' },
    { value: '{YYYY}', label: 'Year (YYYY)' },
    { value: '{yyyy}', label: 'Year (yyyy)' },
    { value: '{YY}', label: 'Year (YY)' },
    { value: '{yy}', label: 'Year (yy)' }
  ]
}));

// Mock the formatUtils
jest.mock('commonApp/formatUtils', () => ({
  generateWeekName: jest.fn((format: string, week: string) => {
    return `Week ${week} - ${format}`;
  })
}));

describe('WeekNameFormatPanel', () => {
  const defaultProps = {
    isOpen: true,
    onClose: jest.fn(),
    onSave: jest.fn(),
    currentFormat: '{ww}',
    hasAutoGeneratedContent: true
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should render without crashing', () => {
    render(<WeekNameFormatPanel {...defaultProps} />);
    expect(screen.getByTestId('format-panel')).toBeInTheDocument();
  });

  it('should pass correct props to FormatPanel', () => {
    render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-panel-title')).toHaveTextContent('Week Name Format');
    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('{ww}');
    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('true');
    expect(screen.getByTestId('format-panel-has-auto-generated')).toHaveTextContent('true');
  });

  it('should generate preview text correctly', () => {
    const { generateWeekName } = require('commonApp/formatUtils');
    render(<WeekNameFormatPanel {...defaultProps} />);

    expect(generateWeekName).toHaveBeenCalledWith('{ww}', '1');
    // The preview text is generated by the mock FormatPanel, not the actual component
    expect(screen.getByTestId('format-panel-preview')).toBeInTheDocument();
  });

  it('should handle close action', () => {
    render(<WeekNameFormatPanel {...defaultProps} />);

    const closeButton = screen.getByTestId('format-panel-close');
    fireEvent.click(closeButton);

    expect(defaultProps.onClose).toHaveBeenCalledTimes(1);
  });

  it('should handle save action', () => {
    render(<WeekNameFormatPanel {...defaultProps} />);

    const saveButton = screen.getByTestId('format-panel-save');
    fireEvent.click(saveButton);

    expect(defaultProps.onSave).toHaveBeenCalledWith('new-format');
  });

  it('should handle different current formats', () => {
    const propsWithDifferentFormat = {
      ...defaultProps,
      currentFormat: '{YYYY}'
    };

    render(<WeekNameFormatPanel {...propsWithDifferentFormat} />);

    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('{YYYY}');
  });

  it('should handle hasAutoGeneratedContent as false', () => {
    const propsWithAutoGeneratedFalse = {
      ...defaultProps,
      hasAutoGeneratedContent: false
    };

    render(<WeekNameFormatPanel {...propsWithAutoGeneratedFalse} />);

    expect(screen.getByTestId('format-panel-has-auto-generated')).toHaveTextContent('false');
  });

  it('should handle hasAutoGeneratedContent as undefined (default true)', () => {
    const propsWithoutAutoGenerated = {
      isOpen: true,
      onClose: jest.fn(),
      onSave: jest.fn(),
      currentFormat: '{ww}'
    };

    render(<WeekNameFormatPanel {...propsWithoutAutoGenerated} />);

    expect(screen.getByTestId('format-panel-has-auto-generated')).toHaveTextContent('true');
  });

  it('should handle isOpen as false', () => {
    const propsWithClosed = {
      ...defaultProps,
      isOpen: false
    };

    render(<WeekNameFormatPanel {...propsWithClosed} />);

    expect(screen.getByTestId('format-panel-is-open')).toHaveTextContent('false');
  });

  it('should pass format options to FormatPanel', () => {
    render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-option-0')).toHaveTextContent('Week Number (ww) - {ww}');
    expect(screen.getByTestId('format-option-1')).toHaveTextContent('Year (YYYY) - {YYYY}');
    expect(screen.getByTestId('format-option-2')).toHaveTextContent('Year (yyyy) - {yyyy}');
    expect(screen.getByTestId('format-option-3')).toHaveTextContent('Year (YY) - {YY}');
    expect(screen.getByTestId('format-option-4')).toHaveTextContent('Year (yy) - {yy}');
  });

  it('should call generateWeekName with correct parameters for preview', () => {
    const { generateWeekName } = require('commonApp/formatUtils');
    const propsWithFormat = {
      ...defaultProps,
      currentFormat: '{YYYY}'
    };

    render(<WeekNameFormatPanel {...propsWithFormat} />);

    expect(generateWeekName).toHaveBeenCalledWith('{YYYY}', '1');
  });

  it('should handle component unmounting', () => {
    const { unmount } = render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-panel')).toBeInTheDocument();
    unmount();
  });

  it('should handle prop changes', () => {
    const { rerender } = render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('{ww}');

    const newProps = {
      ...defaultProps,
      currentFormat: '{yyyy}'
    };

    rerender(<WeekNameFormatPanel {...newProps} />);

    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('{yyyy}');
  });

  it('should handle multiple format changes', () => {
    const { generateWeekName } = require('commonApp/formatUtils');
    const { rerender } = render(<WeekNameFormatPanel {...defaultProps} />);

    expect(generateWeekName).toHaveBeenCalledWith('{ww}', '1');

    const newProps = {
      ...defaultProps,
      currentFormat: '{YYYY}'
    };

    rerender(<WeekNameFormatPanel {...newProps} />);

    expect(generateWeekName).toHaveBeenCalledWith('{YYYY}', '1');
  });

  it('should handle empty current format', () => {
    const propsWithEmptyFormat = {
      ...defaultProps,
      currentFormat: ''
    };

    render(<WeekNameFormatPanel {...propsWithEmptyFormat} />);

    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('');
  });

  it('should handle undefined current format', () => {
    const propsWithUndefinedFormat = {
      ...defaultProps,
      currentFormat: undefined as any
    };

    render(<WeekNameFormatPanel {...propsWithUndefinedFormat} />);

    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('');
  });

  it('should handle null current format', () => {
    const propsWithNullFormat = {
      ...defaultProps,
      currentFormat: null as any
    };

    render(<WeekNameFormatPanel {...propsWithNullFormat} />);

    expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent('');
  });

  it('should handle rapid prop changes', () => {
    const { rerender } = render(<WeekNameFormatPanel {...defaultProps} />);

    // Change format multiple times
    const formats = ['{ww}', '{YYYY}', '{yyyy}', '{YY}', '{yy}'];
    
    formats.forEach(format => {
      const newProps = {
        ...defaultProps,
        currentFormat: format
      };
      rerender(<WeekNameFormatPanel {...newProps} />);
      expect(screen.getByTestId('format-panel-current-format')).toHaveTextContent(format);
    });
  });

  it('should handle all callback functions', () => {
    const mockOnClose = jest.fn();
    const mockOnSave = jest.fn();
    
    const propsWithCallbacks = {
      ...defaultProps,
      onClose: mockOnClose,
      onSave: mockOnSave
    };

    render(<WeekNameFormatPanel {...propsWithCallbacks} />);

    // Test close callback
    fireEvent.click(screen.getByTestId('format-panel-close'));
    expect(mockOnClose).toHaveBeenCalledTimes(1);

    // Test save callback
    fireEvent.click(screen.getByTestId('format-panel-save'));
    expect(mockOnSave).toHaveBeenCalledWith('new-format');
  });

  it('should handle edge cases with format options', () => {
    // Mock empty format options
    jest.doMock('../../../../src/constants/periodSetupConstants', () => ({
      WEEK_NAME_FORMAT_OPTIONS: []
    }));

    render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-panel')).toBeInTheDocument();
  });

  it('should handle generateWeekName returning undefined', () => {
    const { generateWeekName } = require('commonApp/formatUtils');
    generateWeekName.mockReturnValue(undefined);

    render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-panel-preview')).toHaveTextContent('');
  });

  it('should handle generateWeekName returning null', () => {
    const { generateWeekName } = require('commonApp/formatUtils');
    generateWeekName.mockReturnValue(null);

    render(<WeekNameFormatPanel {...defaultProps} />);

    expect(screen.getByTestId('format-panel-preview')).toHaveTextContent('');
  });

  it('should handle generateWeekName throwing an error', () => {
    const { generateWeekName } = require('commonApp/formatUtils');
    generateWeekName.mockImplementation(() => {
      throw new Error('Test error');
    });

    // The component will throw an error when generateWeekName throws
    // This is expected behavior since the component calls generateWeekName during render
    expect(() => {
      render(<WeekNameFormatPanel {...defaultProps} />);
    }).toThrow('Test error');
  });
});