import React from 'react';
import FormatPanel from '../FormatPanel/FormatPanel';
import { WEEK_NAME_FORMAT_OPTIONS } from '../../../constants/periodSetupConstants';
import { generateWeekName } from 'commonApp/formatUtils';

export interface WeekNameFormatPanelProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (format: string) => void;
  currentFormat: string;
  hasAutoGeneratedContent?: boolean;
}

const WeekNameFormatPanel: React.FC<WeekNameFormatPanelProps> = ({
  isOpen,
  onClose,
  onSave,
  currentFormat,
  hasAutoGeneratedContent = true,
}) => {
  const generatePreview = (format: string): string => {
    // Generate preview based on the selected format
    // Use the actual week name values (week 1, current year)
    return generateWeekName(format, '1');
  };

  const handleSave = (format: string) => {
    onSave(format);
  };

  return (
    <FormatPanel
      isOpen={isOpen}
      onClose={onClose}
      onSave={handleSave}
      title="Week Name Format"
      formatOptions={WEEK_NAME_FORMAT_OPTIONS}
      currentFormat={currentFormat}
      previewText={generatePreview(currentFormat)}
      hasAutoGeneratedContent={hasAutoGeneratedContent}
      generatePreview={generatePreview}
    />
  );
};

export default WeekNameFormatPanel;
