import React from 'react';
import { Box, Button, Typography } from '@mui/material';

// Mock implementation of FormatPanel
const FormatPanel = ({
  isOpen,
  onClose,
  onSave,
  title,
  formatOptions,
  currentFormat,
  previewText,
  hasAutoGeneratedContent = true,
  generatePreview,
}: any) => {
  
  const [selectedFormat, setSelectedFormat] = React.useState(currentFormat);
  
  const handleSave = () => {
    onSave(selectedFormat);
  };

  const handleChange = (e: any) => {
    setSelectedFormat(e.target.value);
  };

  return (
    <>
      {isOpen && <Box className="format-panel__backdrop" onClick={onClose} />}
      <Box className={`format-panel ${isOpen ? 'format-panel--open' : ''}`}>
        {/* Header */}
        <Box className="format-panel__header">
          <Typography className="format-panel__title">{title}</Typography>
          <div data-testid="custom-tooltip" data-title="Close" data-placement="bottom">
            <button
              aria-label="Close"
              className="format-panel__close-icon"
              onClick={onClose}
            >
              <svg
                width="22"
                height="22"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 32 32"
                fill="currentColor"
                focusable="false"
                preserveAspectRatio="xMidYMid meet"
                aria-hidden="true"
              >
                <path d="M17.4141 16L24 9.4141 22.5859 8 16 14.5859 9.4143 8 8 9.4141 14.5859 16 8 22.5859 9.4143 24 16 17.4141 22.5859 24 24 22.5859 17.4141 16z" />
              </svg>
            </button>
          </div>
        </Box>

        {/* Content */}
        <Box className="format-panel__content">
          <Typography className="format-panel__section-title">
            {title.replace(' Format', ' Naming Formats')}
          </Typography>

          <div className="format-panel__radio-group" role="radiogroup">
            {formatOptions.map((option: any) => (
              <label key={option.value} className="format-panel__radio-item">
                <div data-testid="custom-radio">
                  <div data-testid={`radio-option-${option.value}`}>
                    <input
                      type="radio"
                      name="radio-group"
                      value={option.value}
                      checked={selectedFormat === option.value}
                      onChange={handleChange}
                      readOnly
                    />
                    <label>{option.label}</label>
                  </div>
                </div>
                <span className="MuiFormControlLabel-label">
                  <div className="format-panel__radio-label">
                    <p className="format-panel__radio-text">{option.label}</p>
                    {option.isDefault && (
                      <p className="format-panel__default-text">Default</p>
                    )}
                  </div>
                </span>
              </label>
            ))}
          </div>
        </Box>

        {/* Preview Section */}
        <Box className="format-panel__preview-section">
          <Typography className="format-panel__preview-label">Preview</Typography>
          <Typography className="format-panel__preview-text">
            {generatePreview ? generatePreview(selectedFormat) : previewText}
          </Typography>
        </Box>

        {/* Actions */}
        <Box className="format-panel__actions">
          <Button className="format-panel__cancel-btn" onClick={onClose}>
            Cancel
          </Button>
          <Button className="format-panel__save-btn" onClick={handleSave}>
            Save
          </Button>
        </Box>
      </Box>
    </>
  );
};

export default FormatPanel;
